vich_uploader:
    db_driver: orm

    mappings:
        tvshows:
            uri_prefix: /images/tvshows
            upload_destination: '%kernel.project_dir%/public/images/tvshows'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer